services:
  phlegethon:
    image: ${PHL_IMAGE_NAME:-phlegethon:ubuntu}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ubuntu:24.04}
        INSTALL_CMD: ${INSTALL_CMD:-}
    environment:
      TEST_CASE: ${TEST_CASE:-tests/hotbubble}
      MPI_RANKS: ${MPI_RANKS:-4}
      OMPI_ALLOW_RUN_AS_ROOT: "1"
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: "1"
    working_dir: /opt/phlegethon
    volumes:
      - ./:/opt/phlegethon
    tty: true
    stdin_open: true
